'use server';
/**
 * @fileOverview Technical Signal Analysis Agent.
 *
 * - analyzeSignal - Analyzes a trading signal using technical metrics and performance data.
 * - AnalyzeSignalInput - Input schema containing signal and market data.
 * - AnalyzeSignalOutput - Structured technical outlook and recommendation.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

const AnalyzeSignalInputSchema = z.object({
  symbol: z.string(),
  type: z.enum(['BUY', 'SELL', 'NEUTRAL']),
  entryPrice: z.number(),
  currentPrice: z.number(),
  timeframe: z.string(),
  maxUpside: z.number().optional(),
  maxDrawdown: z.number().optional(),
  assetType: z.string().optional(),
  exchange: z.string().optional(),
});
export type AnalyzeSignalInput = z.infer<typeof AnalyzeSignalInputSchema>;

const AnalyzeSignalOutputSchema = z.object({
  recommendation: z.enum(['STRONG BUY', 'BUY', 'HOLD', 'WAIT FOR PULLBACK', 'AVOID']),
  confidenceScore: z.number().describe('A score from 0-100 indicating the AI confidence in the recommendation.'),
  technicalReasoning: z.string().describe('A concise technical explanation for the recommendation.'),
  riskAssessment: z.string().describe('Potential risks associated with this specific signal/asset.'),
  suggestedStopLoss: z.number().optional().describe('A technically suggested stop loss based on volatility.'),
  suggestedTakeProfit: z.number().optional().describe('A technically suggested target price.'),
});
export type AnalyzeSignalOutput = z.infer<typeof AnalyzeSignalOutputSchema>;

export async function analyzeSignal(input: AnalyzeSignalInput): Promise<AnalyzeSignalOutput> {
  return analyzeSignalFlow(input);
}

const prompt = ai.definePrompt({
  name: 'analyzeSignalPrompt',
  input: { schema: AnalyzeSignalInputSchema },
  output: { schema: AnalyzeSignalOutputSchema },
  prompt: `You are a Senior Quantitative Analyst at a top-tier hedge fund. Your specialty is analyzing short-term and swing trading signals.

Analyze the following trading signal and provide a professional recommendation:

Asset: {{symbol}} ({{assetType}})
Signal Type: {{type}}
Timeframe: {{timeframe}}
Entry Price: {{entryPrice}}
Current Price: {{currentPrice}}
Max Upside Achieved: {{maxUpside}}%
Max Drawdown Achieved: {{maxDrawdown}}%

### Context:
- The signal was generated by a TradingView indicator on the {{exchange}} exchange.
- Current Performance: {{#if currentPrice}} The price has moved from {{entryPrice}} to {{currentPrice}}. {{else}} Not available yet. {{/if}}

### Instructions:
1. Evaluate if the entry is still valid or if the price has moved too far from the alert level.
2. Consider the timeframe - smaller timeframes (1m-15m) require tighter risk management.
3. If the signal has already achieved significant upside but is currently pulling back, suggest if it's a re-entry or an exit.
4. Set the confidence score based on the risk-reward ratio.
5. Provide a realistic suggested Stop Loss and Take Profit based on the entry price.`,
});

const analyzeSignalFlow = ai.defineFlow(
  {
    name: 'analyzeSignalFlow',
    inputSchema: AnalyzeSignalInputSchema,
    outputSchema: AnalyzeSignalOutputSchema,
  },
  async (input) => {
    const { output } = await prompt(input);
    if (!output) throw new Error('AI analysis failed');
    return output;
  }
);
