steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build'
    args:
      - 'build'
      - '--no-cache'
      - '-f'
      - 'Dockerfile.liquidity-ws'
      - '-t'
      - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/liquidity-ws:latest'
      - '.'

  # Step 2: Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push'
    args:
      - 'push'
      - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/liquidity-ws:latest'

images:
  - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/liquidity-ws:latest'

options:
  logging: CLOUD_LOGGING_ONLY
